### ISSUE TITLE
Hope to provide the musl build version, as many servers do not have such a higher version of GLIBC

### ISSUE THREAD

**Issue by LuYanFCP** [JakWai01/lurk#27]

**Comment by orhun** [comment]
See https://github.com/JakWai01/lurk/issues/4#issuecomment-2342903278

Unfortunately `libc` crate does not seem to have that type for [x86_64-unknown-linux-musl](https://docs.rs/libc/latest/x86_64-unknown-linux-musl/libc/index.html) target.
