### ISSUE TITLE
follow-forks flag seems to be not working correctly 

### ISSUE THREAD

**Issue by sigmaSd** [JakWai01/lurk#5]
Hello, thanks for this nice project

I tried debugging a project with lurk but I noticed 2 problems with `-f`:
- Sometimes it hang and doesn't terminate
- When it does terminate  paradoxically the output is really short its shorter then without `-f` flag

For example here is a comparison of running without `-f` and with `-f`

*without `-f`*:
https://pastebin.com/4bD03gYG
*with `-f`*:
https://pastebin.com/e6AjTwRm

Reproduction

`lurk -f deno run --unstable -A https://pastebin.com/raw/XkLSzG34`

If you try this multiple times sometimes it hangs on epollwait, and when it succeeds the output is very short, shorter then without `-f` flag.

**meta**:
- Linux 5.18.13-arch1-1 1 SMP PREEMPT_DYNAMIC Fri, 22 Jul 2022 13:05:04 +0000 x86_64 GNU/Linux
- deno 1.24.0
- lurk 0.2.9

**Comment by sigmaSd** [comment]
Maybe its too early for this project for this kind of issues (deno alone is a complex program that probably will execute all kind of different edge cases)

**Comment by JakWai01** [comment]
Totally not! This is a very important issue to solve. I agree that there are probably other things should probably work first (e.g. correct error codes, displaying structs as arguments) but this one is still high on the list. I'll try to continue working on lurk ASAP.

**Comment by sigmaSd** [comment]
No rush thanks a lot for this project, we can learn strace in a readable language thanks to your work
